# This file is managed by Qt Creator, do not edit!

set("ANDROID_STL" "c++_shared" CACHE "STRING" "" FORCE)
set("CMAKE_PREFIX_PATH" "C:/Qt/6.10.2/android_x86_64" CACHE "PATH" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "C:/Qt/6.10.2/android_x86_64/bin/qmake.bat" CACHE "FILEPATH" "" FORCE)
set("CMAKE_BUILD_TYPE" "Debug" CACHE "STRING" "" FORCE)
set("QT_MAINTENANCE_TOOL" "C:/Qt/MaintenanceTool.exe" CACHE "FILEPATH" "" FORCE)
set("ANDROID_NDK" "C:/Users/PC/AppData/Local/Android/Sdk/ndk/27.2.12479018" CACHE "PATH" "" FORCE)
set("CMAKE_COLOR_DIAGNOSTICS" "ON" CACHE "BOOL" "" FORCE)
set("ANDROID_USE_LEGACY_TOOLCHAIN_FILE" "OFF" CACHE "BOOL" "" FORCE)
set("QT_USE_TARGET_ANDROID_BUILD_DIR" "ON" CACHE "BOOL" "" FORCE)
set("QT_HOST_PATH" "C:/Qt/6.10.2/mingw_64" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER" "C:/Users/PC/AppData/Local/Android/Sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe" CACHE "FILEPATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "C:/Users/PC/AppData/Local/Android/Sdk/ndk/27.2.12479018/build/cmake/android.toolchain.cmake" CACHE "FILEPATH" "" FORCE)
set("ANDROID_SDK_ROOT" "C:/Users/PC/AppData/Local/Android/Sdk" CACHE "PATH" "" FORCE)
set("CMAKE_FIND_ROOT_PATH" "C:/Qt/6.10.2/android_x86_64" CACHE "PATH" "" FORCE)
set("CMAKE_CXX_FLAGS_INIT" "" CACHE "STRING" "" FORCE)
set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("QT_NO_GLOBAL_APK_TARGET_PART_OF_ALL" "ON" CACHE "BOOL" "" FORCE)
set("ANDROID_ABI" "x86_64" CACHE "STRING" "" FORCE)
set("CMAKE_CXX_COMPILER" "C:/Users/PC/AppData/Local/Android/Sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" CACHE "FILEPATH" "" FORCE)
set("ANDROID_PLATFORM" "android-28" CACHE "STRING" "" FORCE)
set("CMAKE_PROJECT_INCLUDE_BEFORE" "C:/Users/PC/Documents/Dr.Frake-VPN/.qtc/package-manager/auto-setup.cmake" CACHE "FILEPATH" "" FORCE)
set("FBLINK_ANDROID_TV" "ON" CACHE "BOOL" "" FORCE)